name: build-windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    windows:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.swift }})
        strategy:
            matrix:
                os: [windows-2022, windows-2019]
                swift: [5.7, 5.6.3]
        steps:
            -   name: checkout 
                uses: actions/checkout@v2
            
            -   name: toolchain 
                uses: compnerd/gha-setup-swift@v0.0.1
                with:
                    branch: swift-${{ matrix.swift }}-release
                    tag: ${{ matrix.swift }}-RELEASE
            -   name: build 
                run: | 
                    swift --version
                    swift build